export const rooms = [
    {
        name: 'Habitación Deluxe',
        capacity: 2,
        bedType: 'Cama doble grande',
        dimensions: '30m²',
        includesMeals: true,
        includesWifi: true,
        includesAirConditioning: true,
        privateBathroom: true,
        price: 500,
        isSelected: false,
    },
    {
        name: 'Habitación Económica',
        capacity: 1,
        bedType: 'Cama normal',
        dimensions: '10m²',
        includesMeals: false,
        includesWifi: true,
        includesAirConditioning: true,
        privateBathroom: false,
        price: 150,
        isSelected: false,
    },
    {
        name: 'Habitación Presidencial',
        capacity: 5,
        bedType: 'Cama Grande',
        dimensions: '40m²',
        includesMeals: true,
        includesWifi: true,
        includesAirConditioning: true,
        privateBathroom: true,
        price: 900,
        isSelected: false,
    },
];
